/* Project Euler #2
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

var a = 1;
var b = 2;
var c = 0;
var sumArray = [2];


while(c<4000000){
	c = a + b;
	a = b;
	b = c;
	if (c%2 === 0){
		sumArray.push(c);
	}
}

var sum = sumArray.reduce(function(sum,value){
	return sum + value;
});

console.log(sumArray);
console.log("The sum is: " + sum);

